version: '3.8'

services:
  authservice:
    build:
      context: ./
      dockerfile: AuthService/Dockerfile
    ports:
      - "5216:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${authdb_connectionstring}
    env_file:
      - .env
